In [11]:
import sys
sys.path.insert(0, '../src')

from equityiq.data import get_stock_info, get_price_history, get_financials
import pandas as pd

In [12]:
info = get_stock_info("AAPL")
print(info['longName'])
print(info['currentPrice'])
print(info['marketCap'])

Apple Inc.
298.01
4376979046400

In [13]:
df = get_price_history("AAPL", period="3mo")
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-19 00:00:00-04:00,249.170432,251.598204,247.072375,248.730850,34864100,0.0,0.0
2026-03-20 00:00:00-04:00,247.751733,248.970612,245.773560,247.761734,88331100,0.0,0.0
2026-03-23 00:00:00-04:00,253.736227,254.365652,250.049621,251.258514,40546100,0.0,0.0
2026-03-24 00:00:00-04:00,250.119565,254.595437,249.320298,251.408371,45152300,0.0,0.0
2026-03-25 00:00:00-04:00,253.866115,254.765281,251.368416,252.387466,28476700,0.0,0.0

In [14]:
from equityiq.health import HealthAnalyzer

health = HealthAnalyzer("AAPL")
health.summary()

                                  value
metric
current_ratio              1.070000e+00
quick_ratio                9.060000e-01
debt_to_equity             7.954800e+01
interest_coverage                   NaN
total_debt                 8.471100e+10
roe                        1.414710e+00
roa                        2.622900e-01
gross_margin               4.786200e-01
operating_margin           3.227500e-01
net_margin                 2.715200e-01
revenue_growth             1.660000e-01
earnings_growth            2.180000e-01
earnings_quarterly_growth  1.940000e-01

In [15]:
from equityiq.valuation import ValuationAnalyzer

valuation = ValuationAnalyzer("AAPL")
valuation.summary()
print("\n--- DCF Valuation ---")
print(valuation.intrinsic_value())

--- DCF Valuation ---
{'intrinsic_value_per_share': 107.87, 'margin_of_safety_price': 80.91, 'current_price': 298.01, 'upside_downside_pct': -63.8, 'is_undervalued': False}

In [16]:
from equityiq.signals import SignalAnalyzer

signals = SignalAnalyzer("AAPL")
print(signals.momentum_signals())
print(signals.quality_signals())
print(signals.valuation_signals())
print("\n--- Overall Score ---")
print(signals.overall_score())

{'current_price': 298.01, 'ma_50': 288.63, 'ma_200': 267.79, 'above_ma_50': True, 'above_ma_200': True, 'golden_cross': True, 'rsi_14': 39.07, 'rsi_signal': 'neutral', 'pct_from_52w_high': -5.45, 'pct_from_52w_low': 49.37}
{'fcf_quality_ratio': 0.82, 'fcf_quality_signal': 'high', 'revenue_growing': True, 'earnings_growing': True, 'healthy_margins': True}
{'pe_ratio': 36.122425, 'pe_signal': 'expensive', 'pb_signal': 'expensive', 'peg_signal': 'overvalued'}

--- Overall Score ---
{'ticker': 'AAPL', 'score': 70, 'recommendation': 'BUY', 'momentum_score': 3, 'quality_score': 4, 'valuation_score': 0}

In [17]:
from equityiq.report import Report

report = Report("AAPL")
print(report.summary())

============================================================
  EQUITYIQ REPORT — Apple Inc. (AAPL)
============================================================
  Sector:      Technology
  Industry:    Consumer Electronics
  Country:     United States
  Market Cap:  $4376.98B
  Generated:   2026-06-21 18:17:45
============================================================

--- FINANCIAL HEALTH ---
  Liquidity
    Current Ratio:       1.07
    Quick Ratio:         0.91
  Debt
    Debt to Equity:      79.55
    Interest Coverage:   N/A
  Profitability
    ROE:                 141.5%
    ROA:                 26.2%
    Gross Margin:        47.9%
    Net Margin:          27.2%
  Growth
    Revenue Growth:      16.6%
    Earnings Growth:     21.8%

--- VALUATION ---
  Market Multiples
    P/E (trailing):      36.12
    P/E (forward):       31.04
    P/B:                 41.05
    P/S:                 9.70
    PEG:                 2.41
    EV/EBITDA:           27.46
  DCF Valuation (simplified)
    Intrinsic Value:     $107.87
    Safety Price (25%):  $80.91
    Upside/Downside:     -63.8%
    Undervalued:         No

--- SIGNALS ---
  Momentum
    Price:               $298.01
    MA 50:               $288.63
    MA 200:              $267.79
    Above MA50:          Yes
    Above MA200:         Yes
    Golden Cross:        Yes
    RSI (14):            39.07 — neutral
    From 52w High:       -5.45%
    From 52w Low:        49.37%
  Quality
    FCF Quality:         high
    Revenue Growing:     Yes
    Earnings Growing:    Yes
    Healthy Margins:     Yes
  Valuation Signals
    P/E Signal:          expensive
    P/B Signal:          expensive
    PEG Signal:          overvalued

============================================================
  🟢  RECOMMENDATION: BUY  |  SCORE: 70/100
============================================================
  Momentum Score:   3/4
  Quality Score:    4/4
  Valuation Score:  0/2
============================================================

In [18]:
tickers = ["AAPL", "MSFT", "GOOGL"]
dataframes = []

for t in tickers:
    r = Report(t)
    df = r.to_dataframe()
    df["ticker"] = t
    dataframes.append(df)

comparison = pd.concat(dataframes).pivot_table(
    index="metric", columns="ticker", values="value", aggfunc="first"
)
print(comparison)

ticker                                 AAPL          GOOGL            MSFT
metric
current_ratio                          1.07          1.922           1.283
debt_to_equity                       79.548         20.026          30.271
dividend_rate                          1.08           0.88            3.64
dividend_yield                         0.36           0.24            0.96
earnings_growth                       0.218           0.82           0.234
earnings_quarterly_growth             0.194          0.812           0.231
ev_to_ebitda                         27.462          27.45          15.535
ev_to_revenue                         9.731         10.481           9.003
five_year_avg_dividend_yield            0.5            NaN            0.79
forward_pe                        31.040802      25.387682       19.611391
gross_margin                        0.47862        0.60368         0.68309
momentum_score                            3              4               0
net_margin                          0.27152        0.37919         0.39342
operating_margin                    0.32275        0.36121         0.46326
payout_ratio                         0.1259         0.0641          0.2073
pb_ratio                           41.04821       9.313914        6.802087
pe_ratio                          36.122425      28.093893       22.569899
peg_ratio                              2.41           1.45            1.17
ps_ratio                           9.695551      10.629429        8.855128
quality_score                             4              3               3
quick_ratio                           0.906          1.707           1.142
recommendation                          BUY            BUY            HOLD
revenue_growth                        0.166          0.218           0.183
roa                                 0.26229        0.14641         0.14814
roe                                 1.41471        0.38885         0.34014
score                                    70             80              50
total_debt                    84710998016.0  95875997696.0  125431996416.0
valuation_score                           0              1               2

In [19]:
from equityiq.valuation import ValuationAnalyzer

v = ValuationAnalyzer("AAPL")
print(v.intrinsic_value())

{'intrinsic_value_per_share': 107.87, 'margin_of_safety_price': 80.91, 'current_price': 298.01, 'upside_downside_pct': -63.8, 'is_undervalued': False}

In [1]:
from equityiq.data import get_balance_sheet, get_cash_flow, get_income_statement

is_df = get_income_statement("META")
bs_df = get_balance_sheet("META")
cf_df = get_cash_flow("META")

print("=== Income Statement ===")
print(is_df)
print("\n=== Balance Sheet ===")
print(bs_df)
print("\n=== Cash Flow ===")
print(cf_df)

=== Income Statement ===
                  2021          2022          2023          2024          2025
revenue            NaN  1.166090e+05  1.349020e+05  1.645010e+05  2.009660e+05
gross_profit       NaN  9.136000e+04  1.089430e+05  1.343400e+05  1.647910e+05
ebit               NaN  2.900400e+04  4.787400e+04  7.137800e+04  8.709700e+04
ebitda             NaN  3.769000e+04  5.905200e+04  8.687600e+04  1.057130e+05
da                 NaN  8.686000e+03  1.117800e+04  1.549800e+04  1.861600e+04
net_income         NaN  2.320000e+04  3.909800e+04  6.236000e+04  6.045800e+04
interest_expense   NaN  1.850000e+02  4.460000e+02  7.150000e+02  1.165000e+03
interest_income    NaN  4.610000e+02  1.639000e+03  2.517000e+03  2.123000e+03
tax_expense        NaN  5.619000e+03  8.330000e+03  8.303000e+03  2.547400e+04
eps_diluted        NaN  8.590000e+00  1.487000e+01  2.386000e+01  2.349000e+01
shares_diluted     NaN  2.702000e+09  2.629000e+09  2.614000e+09  2.574000e+09

=== Balance Sheet ===
                              2021      2022      2023      2024      2025
cash                           NaN   14681.0   41862.0   43889.0   35873.0
marketable_securities          NaN    6201.0    6141.0    6070.0   27524.0
accounts_receivable            NaN   13466.0   16169.0   16994.0   19769.0
inventories                    NaN       NaN       NaN       NaN       NaN
total_current_assets           NaN   59549.0   85365.0  100045.0  108722.0
total_assets                   NaN  185727.0  229623.0  276054.0  366021.0
accounts_payable               NaN    4990.0    4849.0    7687.0    8894.0
unearned_revenue               NaN       NaN       NaN       NaN       NaN
short_term_debt                NaN       NaN       NaN       NaN       NaN
long_term_debt                 NaN    9923.0   18385.0   28826.0   58744.0
operating_lease_current      561.0       NaN       NaN       NaN       NaN
operating_lease_non_current    NaN       NaN       NaN       NaN       NaN
total_equity                   NaN  125713.0  153168.0  182637.0  217243.0

=== Cash Flow ===
                          2021     2022     2023     2024      2025
cfo                        NaN  50475.0  71113.0  91328.0  115800.0
capex                      NaN -31186.0 -27045.0 -37256.0  -69691.0
capex_maintenance          NaN  -8686.0 -11178.0 -15498.0  -18616.0
capex_expansion            NaN -22500.0 -15867.0 -21758.0  -51075.0
da                         NaN   8686.0  11178.0  15498.0   18616.0
acquisitions               NaN      NaN      NaN      NaN       NaN
repurchases                NaN -27956.0 -19774.0 -30125.0  -26248.0
dividends                  NaN      0.0      0.0  -5072.0   -5324.0
stock_based_compensation   NaN  11992.0  14027.0  16690.0   20427.0
net_change_in_cash         NaN   -631.0  27118.0   3397.0   -6573.0

In [4]:
from importlib import reload
import equityiq.fundamental as f
reload(f)
from equityiq.fundamental import FundamentalAnalyzer

fa = FundamentalAnalyzer("META")
fa.summary()

=================================================================
  FUNDAMENTAL ANALYSIS — Meta Platforms, Inc. (META)
  Currency: USD | Values in millions
=================================================================

--- INCOME STATEMENT ---
                         2022       2023       2024       2025
Revenue             $116,609M  $134,902M  $164,501M  $200,966M
Revenue Y/Y %               -      15.7%      21.9%      22.2%
Gross Profit         $91,360M  $108,943M  $134,340M  $164,791M
Gross Margin %          78.3%      80.8%      81.7%      82.0%
EBITDA               $37,690M   $59,052M   $86,876M  $105,713M
EBITDA Margin %         32.3%      43.8%      52.8%      52.6%
EBITDA Y/Y %                -      56.7%      47.1%      21.7%
D&A                   $8,686M   $11,178M   $15,498M   $18,616M
EBIT                 $29,004M   $47,874M   $71,378M   $87,097M
EBIT Margin %           24.9%      35.5%      43.4%      43.3%
EBIT Y/Y %                  -      65.1%      49.1%      22.0%
Interest Expense      $185.0M    $446.0M    $715.0M    $1,165M
Interest Income       $461.0M    $1,639M    $2,517M    $2,123M
Total Net Interest    $276.0M    $1,193M    $1,802M    $958.0M
Tax Expense           $5,619M    $8,330M    $8,303M   $25,474M
Tax Rate %              19.2%      17.0%      11.3%      28.9%
Net Income           $23,200M   $39,098M   $62,360M   $60,458M
Net Margin %            19.9%      29.0%      37.9%      30.1%
Net Income Y/Y %            -      68.5%      59.5%      -3.1%
EPS Diluted             $8.59     $14.87     $23.86     $23.49
EPS Y/Y %                   -      73.1%      60.5%      -1.6%
Shares Diluted (M)     2,702M     2,629M     2,614M     2,574M
Shares Y/Y %                -      -2.7%      -0.6%      -1.5%

--- CAGR (full available history) ---
Revenue CAGR       19.9%
EBITDA CAGR        41.0%
EBIT CAGR          44.3%
Net Income CAGR    37.6%
EPS CAGR           39.8%

--- FREE CASH FLOW ---
                             2021      2022       2023       2024       2025
EBITDA                          -  $37,690M   $59,052M   $86,876M  $105,713M
(-) CapEx Maintenance           -  $-8,686M  $-11,178M  $-15,498M  $-18,616M
(-) Net Interest                -   $276.0M    $1,193M    $1,802M    $958.0M
(-) Taxes Paid                  -  $-5,619M   $-8,330M   $-8,303M  $-25,474M
(-) Change in WC                -  $-8,476M   $-2,844M    $2,013M   $-1,568M
Free Cash Flow                  -  $15,185M   $37,893M   $66,890M   $61,013M
FCF Margin %                    -     13.0%      28.1%      40.7%      30.4%
FCF Y/Y %                       -         -     149.5%      76.5%      -8.8%
FCF per Share                   -     $5.62     $14.41     $25.59     $23.70
Cash Conversion (FCF/EBITDA)    -     40.3%      64.2%      77.0%      57.7%

--- FCF EFFICIENCY ---
                               2021   2022   2023   2024   2025 Median
CapEx Maintenance / Revenue       -   7.4%   8.3%   9.4%   9.3%   8.8%
Working Capital / Revenue         -   7.3%   8.4%   5.7%   5.4%   6.5%
FCF Margin (FCF / Revenue)        -  13.0%  28.1%  40.7%  30.4%  29.2%
Cash Conversion (FCF / EBITDA)    -  40.3%  64.2%  77.0%  57.7%  60.9%

--- CAPITAL ALLOCATION (% of FCF) ---
                2021    2022   2023   2024   2025 Median
CapEx Expansion    -  148.2%  41.9%  32.5%  83.7%  62.8%
Acquisitions       -    0.0%   0.0%   0.0%   0.0%   0.0%
Repurchases        -  184.1%  52.2%  45.0%  43.0%  48.6%
Dividends          -    0.0%   0.0%   7.6%   8.7%   3.8%

--- ROIC & INVESTED CAPITAL ---
                                    2021       2022       2023       2024       2025     Median
NOPAT (EBIT x (1-t))                   -   $23,438M   $39,747M   $63,279M   $61,900M   $50,823M
Cash                                   -   $14,681M   $41,862M   $43,889M   $35,873M   $35,873M
(-) Marketable Securities              -    $6,201M    $6,141M    $6,070M   $27,524M    $6,141M
(+) Short-Term Debt                    -          -          -          -          -          -
(+) Long-Term Debt                     -    $9,923M   $18,385M   $28,826M   $58,744M   $18,385M
(+) Operating Lease Current      $561.0M          -          -          -          -          -
(+) Operating Lease Non-Current        -          -          -          -          -          -
(+) Equity                             -  $125,713M  $153,168M  $182,637M  $217,243M  $153,168M
Invested Capital                 $561.0M  $114,754M  $123,550M  $161,504M  $212,590M  $123,550M
ROIC                                   -      20.4%      32.2%      39.2%      29.1%      30.6%
ROE                                    -      18.5%      25.5%      34.1%      27.8%      26.7%

--- RED FLAGS ---
                2022   2023   2024   2025
SBC / Revenue  10.3%  10.4%  10.1%  10.2%

Years with revenue decline           0
Years with FCF < 0                   0
Years with poor ROIC (<10%)          0
Years with Net Debt/EBITDA > 2.5x    0

In [1]:
from equityiq.projection import Projector

# Escenario 1: usando medias históricas como default
p = Projector("META")
p.summary()

# Escenario 2: introduciendo tus propios supuestos (como en el Excel)
p2 = Projector("META", revenue_growth=0.20, ebit_margin=0.40, tax_rate=0.15)
p2.summary()

=================================================================
  PROJECTION — Meta Platforms, Inc. (META)
  Currency: USD | Values in millions
=================================================================

--- ASSUMPTIONS ---
Revenue Growth (annual)      21.9%
EBIT Margin                  39.4%
Tax Rate                     18.1%
CapEx Maint. / Revenue        8.8%
Working Capital / Revenue     6.5%
D&A / Revenue                 8.8%
Base Year                     2025
Projected Years                  5

--- PROJECTED INCOME STATEMENT ---
                        2026e      2027e      2028e      2029e      2030e
Revenue             $245,060M  $298,829M  $364,396M  $444,348M  $541,843M
Revenue Y/Y %           21.9%      21.9%      21.9%      21.9%      21.9%
EBITDA              $118,090M  $144,000M  $175,596M  $214,123M  $261,104M
EBITDA Margin %         48.2%      48.2%      48.2%      48.2%      48.2%
D&A                  $21,503M   $26,221M   $31,974M   $38,990M   $47,545M
EBIT                 $96,587M  $117,779M  $143,621M  $175,133M  $213,560M
EBIT Margin %           39.4%      39.4%      39.4%      39.4%      39.4%
Tax Expense          $17,466M   $21,299M   $25,972M   $31,671M   $38,619M
Tax Rate %              18.1%      18.1%      18.1%      18.1%      18.1%
Net Income           $79,121M   $96,480M  $117,649M  $143,463M  $174,940M
Net Margin %            32.3%      32.3%      32.3%      32.3%      32.3%
EPS Diluted            $30.74     $37.48     $45.71     $55.74     $67.96
Shares Diluted (M)     2,574M     2,574M     2,574M     2,574M     2,574M

--- PROJECTED FREE CASH FLOW ---
                                  2026e      2027e      2028e      2029e      2030e
EBITDA                        $118,090M  $144,000M  $175,596M  $214,123M  $261,104M
(-) CapEx Maintenance         $-21,503M  $-26,221M  $-31,974M  $-38,990M  $-47,545M
(-) Taxes Paid                $-17,466M  $-21,299M  $-25,972M  $-31,671M  $-38,619M
(-) Change in WC               $-4,964M   $-3,475M   $-4,238M   $-5,168M   $-6,301M
Free Cash Flow                 $74,157M   $93,005M  $113,412M  $138,295M  $168,639M
FCF Margin %                      30.3%      31.1%      31.1%      31.1%      31.1%
FCF Y/Y %                         21.5%      25.4%      21.9%      21.9%      21.9%
FCF per Share                    $28.81     $36.13     $44.06     $53.73     $65.52
Cash Conversion (FCF/EBITDA)      62.8%      64.6%      64.6%      64.6%      64.6%

--- COMBINED VIEW (Historical + Projected) ---
                                   2022       2023       2024       2025      2026e      2027e      2028e      2029e      2030e
Revenue                       $116,609M  $134,902M  $164,501M  $200,966M  $245,060M  $298,829M  $364,396M  $444,348M  $541,843M
Revenue Y/Y %                         -      15.7%      21.9%      22.2%      21.9%      21.9%      21.9%      21.9%      21.9%
EBITDA                         $37,690M   $59,052M   $86,876M  $105,713M  $118,090M  $144,000M  $175,596M  $214,123M  $261,104M
EBITDA Margin %                   32.3%      43.8%      52.8%      52.6%      48.2%      48.2%      48.2%      48.2%      48.2%
D&A                             $8,686M   $11,178M   $15,498M   $18,616M   $21,503M   $26,221M   $31,974M   $38,990M   $47,545M
EBIT                           $29,004M   $47,874M   $71,378M   $87,097M   $96,587M  $117,779M  $143,621M  $175,133M  $213,560M
EBIT Margin %                     24.9%      35.5%      43.4%      43.3%      39.4%      39.4%      39.4%      39.4%      39.4%
Tax Expense                     $5,619M    $8,330M    $8,303M   $25,474M   $17,466M   $21,299M   $25,972M   $31,671M   $38,619M
Tax Rate %                        19.2%      17.0%      11.3%      28.9%      18.1%      18.1%      18.1%      18.1%      18.1%
Net Income                     $23,200M   $39,098M   $62,360M   $60,458M   $79,121M   $96,480M  $117,649M  $143,463M  $174,940M
Net Margin %                      19.9%      29.0%      37.9%      30.1%      32.3%      32.3%      32.3%      32.3%      32.3%
EPS Diluted                       $8.59     $14.87     $23.86     $23.49     $30.74     $37.48     $45.71     $55.74     $67.96
Shares Diluted (M)               2,702M     2,629M     2,614M     2,574M     2,574M     2,574M     2,574M     2,574M     2,574M

EBITDA                         $37,690M   $59,052M   $86,876M  $105,713M  $118,090M  $144,000M  $175,596M  $214,123M  $261,104M
(-) CapEx Maintenance          $-8,686M  $-11,178M  $-15,498M  $-18,616M  $-21,503M  $-26,221M  $-31,974M  $-38,990M  $-47,545M
(-) Taxes Paid                 $-5,619M   $-8,330M   $-8,303M  $-25,474M  $-17,466M  $-21,299M  $-25,972M  $-31,671M  $-38,619M
(-) Change in WC               $-8,476M   $-2,844M    $2,013M   $-1,568M   $-4,964M   $-3,475M   $-4,238M   $-5,168M   $-6,301M
Free Cash Flow                 $15,185M   $37,893M   $66,890M   $61,013M   $74,157M   $93,005M  $113,412M  $138,295M  $168,639M
FCF Margin %                      13.0%      28.1%      40.7%      30.4%      30.3%      31.1%      31.1%      31.1%      31.1%
FCF Y/Y %                             -     149.5%      76.5%      -8.8%      21.5%      25.4%      21.9%      21.9%      21.9%
FCF per Share                     $5.62     $14.41     $25.59     $23.70     $28.81     $36.13     $44.06     $53.73     $65.52
Cash Conversion (FCF/EBITDA)      40.3%      64.2%      77.0%      57.7%      62.8%      64.6%      64.6%      64.6%      64.6%

=================================================================
  PROJECTION — Meta Platforms, Inc. (META)
  Currency: USD | Values in millions
=================================================================

--- ASSUMPTIONS ---
Revenue Growth (annual)      20.0%
EBIT Margin                  40.0%
Tax Rate                     15.0%
CapEx Maint. / Revenue        8.8%
Working Capital / Revenue     6.5%
D&A / Revenue                 8.8%
Base Year                     2025
Projected Years                  5

--- PROJECTED INCOME STATEMENT ---
                        2026e      2027e      2028e      2029e      2030e
Revenue             $241,159M  $289,391M  $347,269M  $416,723M  $500,068M
Revenue Y/Y %           20.0%      20.0%      20.0%      20.0%      20.0%
EBITDA              $117,625M  $141,149M  $169,379M  $203,255M  $243,906M
EBITDA Margin %         48.8%      48.8%      48.8%      48.8%      48.8%
D&A                  $21,161M   $25,393M   $30,472M   $36,566M   $43,879M
EBIT                 $96,464M  $115,756M  $138,908M  $166,689M  $200,027M
EBIT Margin %           40.0%      40.0%      40.0%      40.0%      40.0%
Tax Expense          $14,470M   $17,363M   $20,836M   $25,003M   $30,004M
Tax Rate %              15.0%      15.0%      15.0%      15.0%      15.0%
Net Income           $81,994M   $98,393M  $118,072M  $141,686M  $170,023M
Net Margin %            34.0%      34.0%      34.0%      34.0%      34.0%
EPS Diluted            $31.85     $38.23     $45.87     $55.05     $66.05
Shares Diluted (M)     2,574M     2,574M     2,574M     2,574M     2,574M

--- PROJECTED FREE CASH FLOW ---
                                  2026e      2027e      2028e      2029e      2030e
EBITDA                        $117,625M  $141,149M  $169,379M  $203,255M  $243,906M
(-) CapEx Maintenance         $-21,161M  $-25,393M  $-30,472M  $-36,566M  $-43,879M
(-) Taxes Paid                $-14,470M  $-17,363M  $-20,836M  $-25,003M  $-30,004M
(-) Change in WC               $-4,712M   $-3,117M   $-3,741M   $-4,489M   $-5,387M
Free Cash Flow                 $77,282M   $95,276M  $114,331M  $137,197M  $164,636M
FCF Margin %                      32.0%      32.9%      32.9%      32.9%      32.9%
FCF Y/Y %                         26.7%      23.3%      20.0%      20.0%      20.0%
FCF per Share                    $30.02     $37.01     $44.42     $53.30     $63.96
Cash Conversion (FCF/EBITDA)      65.7%      67.5%      67.5%      67.5%      67.5%

--- COMBINED VIEW (Historical + Projected) ---
                                   2022       2023       2024       2025      2026e      2027e      2028e      2029e      2030e
Revenue                       $116,609M  $134,902M  $164,501M  $200,966M  $241,159M  $289,391M  $347,269M  $416,723M  $500,068M
Revenue Y/Y %                         -      15.7%      21.9%      22.2%      20.0%      20.0%      20.0%      20.0%      20.0%
EBITDA                         $37,690M   $59,052M   $86,876M  $105,713M  $117,625M  $141,149M  $169,379M  $203,255M  $243,906M
EBITDA Margin %                   32.3%      43.8%      52.8%      52.6%      48.8%      48.8%      48.8%      48.8%      48.8%
D&A                             $8,686M   $11,178M   $15,498M   $18,616M   $21,161M   $25,393M   $30,472M   $36,566M   $43,879M
EBIT                           $29,004M   $47,874M   $71,378M   $87,097M   $96,464M  $115,756M  $138,908M  $166,689M  $200,027M
EBIT Margin %                     24.9%      35.5%      43.4%      43.3%      40.0%      40.0%      40.0%      40.0%      40.0%
Tax Expense                     $5,619M    $8,330M    $8,303M   $25,474M   $14,470M   $17,363M   $20,836M   $25,003M   $30,004M
Tax Rate %                        19.2%      17.0%      11.3%      28.9%      15.0%      15.0%      15.0%      15.0%      15.0%
Net Income                     $23,200M   $39,098M   $62,360M   $60,458M   $81,994M   $98,393M  $118,072M  $141,686M  $170,023M
Net Margin %                      19.9%      29.0%      37.9%      30.1%      34.0%      34.0%      34.0%      34.0%      34.0%
EPS Diluted                       $8.59     $14.87     $23.86     $23.49     $31.85     $38.23     $45.87     $55.05     $66.05
Shares Diluted (M)               2,702M     2,629M     2,614M     2,574M     2,574M     2,574M     2,574M     2,574M     2,574M

EBITDA                         $37,690M   $59,052M   $86,876M  $105,713M  $117,625M  $141,149M  $169,379M  $203,255M  $243,906M
(-) CapEx Maintenance          $-8,686M  $-11,178M  $-15,498M  $-18,616M  $-21,161M  $-25,393M  $-30,472M  $-36,566M  $-43,879M
(-) Taxes Paid                 $-5,619M   $-8,330M   $-8,303M  $-25,474M  $-14,470M  $-17,363M  $-20,836M  $-25,003M  $-30,004M
(-) Change in WC               $-8,476M   $-2,844M    $2,013M   $-1,568M   $-4,712M   $-3,117M   $-3,741M   $-4,489M   $-5,387M
Free Cash Flow                 $15,185M   $37,893M   $66,890M   $61,013M   $77,282M   $95,276M  $114,331M  $137,197M  $164,636M
FCF Margin %                      13.0%      28.1%      40.7%      30.4%      32.0%      32.9%      32.9%      32.9%      32.9%
FCF Y/Y %                             -     149.5%      76.5%      -8.8%      26.7%      23.3%      20.0%      20.0%      20.0%
FCF per Share                     $5.62     $14.41     $25.59     $23.70     $30.02     $37.01     $44.42     $53.30     $63.96
Cash Conversion (FCF/EBITDA)      40.3%      64.2%      77.0%      57.7%      65.7%      67.5%      67.5%      67.5%      67.5%

In [1]:
from equityiq.projection import Projector
from equityiq.multiples_valuation import MultiplesValuation
# Un solo valor para todos los años
p = Projector("META", revenue_growth=0.20, ebit_margin=0.40, tax_rate=0.15)
mv = MultiplesValuation("META", projector=p, ev_fcf_target=25, per_target=25,
                         ev_ebitda_target=17, ev_ebit_target=20)
mv.summary()

=================================================================
  VALUATION — Meta Platforms, Inc. (META)
  Current Price:    $577.22
  Market Cap:       $1,465,229M
  Net Debt:         $-4,653M
  Enterprise Value: $1,460,576M
  Currency: USD
=================================================================

--- TARGET MULTIPLES ---
PER Target          25.00x
EV/FCF Target       25.00x
EV/EBITDA Target    17.00x
EV/EBIT Target      20.00x

--- HISTORICAL MULTIPLES ---
             2022    2023    2024    2025  Median
PER        63.16x  37.48x  23.50x  24.24x  30.86x
EV/FCF     96.19x  38.54x  21.84x  23.94x  31.24x
EV/EBITDA  38.75x  24.73x  16.81x  13.82x  20.77x
EV/EBIT    50.36x  30.51x  20.46x  16.77x  25.49x

--- VALUATION SUMMARY (Historical + Projected) ---
                     2022    2023    2024    2025   2026e   2027e   2028e   2029e   2030e
Net Debt / EBITDA  -0.12x  -0.08x  -0.05x  -0.04x  -0.04x  -0.03x  -0.03x  -0.02x  -0.02x
PER                63.16x  37.48x  23.50x  24.24x  17.87x  14.89x  12.41x  10.34x   8.62x
EV/FCF             96.19x  38.54x  21.84x  23.94x  18.90x  15.33x  12.78x  10.65x   8.87x
EV/EBITDA          38.75x  24.73x  16.81x  13.82x  12.42x  10.35x   8.62x   7.19x   5.99x
EV/EBIT            50.36x  30.51x  20.46x  16.77x  15.14x  12.62x  10.51x   8.76x   7.30x

--- TARGET PRICES BY MULTIPLE ---
                           2026e  2027e   2028e   2029e   2030e
PER ex Cash                 $821   $980  $1,171  $1,401  $1,676
EV/FCF                      $752   $927  $1,112  $1,334  $1,601
EV/EBITDA                   $779   $934  $1,120  $1,344  $1,613
EV/EBIT                     $751   $901  $1,081  $1,297  $1,556
Average                     $776   $936  $1,121  $1,344  $1,611
---                          ---    ---     ---     ---     ---
CAGR PER ex Cash           42.2%  30.3%   26.6%   24.8%   23.8%
CAGR EV/FCF                30.4%  26.7%   24.4%   23.3%   22.6%
CAGR EV/EBITDA             34.9%  27.2%   24.7%   23.5%   22.8%
CAGR EV/EBIT               30.2%  25.0%   23.3%   22.4%   21.9%
CAGR Average               34.4%  27.3%   24.8%   23.5%   22.8%
----                        ----   ----    ----    ----    ----
Margin of Safety (EV/FCF)  23.3%  37.7%   48.1%   56.7%   63.9%
Upside Potential (EV/FCF)  30.4%  60.6%   92.7%  131.2%  177.3%

--- BUY PRICE FOR 15% ANNUAL RETURN ---
  Target Return                       15.0%
  Reference Year                      2026e
  EV/FCF Target Price                 $752
  Max Buy Price                       $654.27
  Current Price                       $577.22
  Difference vs Current               -11.8%
  Verdict                             BELOW target price — attractive entry

In [2]:
# Año 1 diferente, resto igual
p = Projector("META")
mv = MultiplesValuation("META", projector=p, ev_fcf_target=25, per_target=25,
                         ev_ebitda_target=17, ev_ebit_target=20)
mv.summary()

=================================================================
  VALUATION — Meta Platforms, Inc. (META)
  Current Price:    $577.22
  Market Cap:       $1,465,229M
  Net Debt:         $-4,653M
  Enterprise Value: $1,460,576M
  Currency: USD
=================================================================

--- TARGET MULTIPLES ---
PER Target          25.00x
EV/FCF Target       25.00x
EV/EBITDA Target    17.00x
EV/EBIT Target      20.00x

--- HISTORICAL MULTIPLES ---
             2022    2023    2024    2025  Median
PER        63.16x  37.48x  23.50x  24.24x  30.86x
EV/FCF     96.19x  38.54x  21.84x  23.94x  31.24x
EV/EBITDA  38.75x  24.73x  16.81x  13.82x  20.77x
EV/EBIT    50.36x  30.51x  20.46x  16.77x  25.49x

--- VALUATION SUMMARY (Historical + Projected) ---
                     2022    2023    2024    2025   2026e   2027e   2028e   2029e   2030e
Net Debt / EBITDA  -0.12x  -0.08x  -0.05x  -0.04x  -0.04x  -0.03x  -0.03x  -0.02x  -0.02x
PER                63.16x  37.48x  23.50x  24.24x  18.52x  15.19x  12.45x  10.21x   8.38x
EV/FCF             96.19x  38.54x  21.84x  23.94x  19.70x  15.70x  12.88x  10.56x   8.66x
EV/EBITDA          38.75x  24.73x  16.81x  13.82x  12.37x  10.14x   8.32x   6.82x   5.59x
EV/EBIT            50.36x  30.51x  20.46x  16.77x  15.12x  12.40x  10.17x   8.34x   6.84x

--- TARGET PRICES BY MULTIPLE ---
                           2026e  2027e   2028e   2029e   2030e
PER ex Cash                 $793   $962  $1,167  $1,418  $1,724
EV/FCF                      $722   $905  $1,103  $1,345  $1,640
EV/EBITDA                   $782   $953  $1,162  $1,416  $1,726
EV/EBIT                     $752   $917  $1,118  $1,363  $1,661
Average                     $762   $934  $1,137  $1,385  $1,688
---                          ---    ---     ---     ---     ---
CAGR PER ex Cash           37.4%  29.1%   26.5%   25.2%   24.5%
CAGR EV/FCF                25.1%  25.2%   24.1%   23.6%   23.2%
CAGR EV/EBITDA             35.4%  28.5%   26.2%   25.1%   24.5%
CAGR EV/EBIT               30.3%  26.0%   24.6%   24.0%   23.5%
CAGR Average               32.1%  27.2%   25.4%   24.5%   23.9%
----                        ----   ----    ----    ----    ----
Margin of Safety (EV/FCF)  20.1%  36.2%   47.7%   57.1%   64.8%
Upside Potential (EV/FCF)  25.1%  56.8%   91.1%  133.0%  184.1%

--- BUY PRICE FOR 15% ANNUAL RETURN ---
  Target Return                       15.0%
  Reference Year                      2026e
  EV/FCF Target Price                 $722
  Max Buy Price                       $627.87
  Current Price                       $577.22
  Difference vs Current               -8.1%
  Verdict                             BELOW target price — attractive entry

In [6]:
# Valor distinto para cada año
p = Projector("META",
              revenue_growth=[0.258, 0.188, 0.168, 0.143, 0.139],
              ebit_margin=[0.354, 0.346, 0.346, 0.369, 0.373],
              tax_rate=0.15)
mv = MultiplesValuation("META", projector=p, ev_fcf_target=25, per_target=25,
                         ev_ebitda_target=17, ev_ebit_target=20)
mv.summary()

=================================================================
  VALUATION — Meta Platforms, Inc. (META)
  Current Price: $577.22 | Currency: USD
=================================================================

--- TARGET MULTIPLES ---
PER Target          25.00x
EV/FCF Target       25.00x
EV/EBITDA Target    17.00x
EV/EBIT Target      20.00x

--- HISTORICAL MULTIPLES ---
             2022    2023    2024    2025  Median
PER        63.16x  37.48x  23.50x  24.24x  30.86x
EV/FCF     96.19x  38.54x  21.84x  23.94x  31.24x
EV/EBITDA  38.75x  24.73x  16.81x  13.82x  20.77x
EV/EBIT    50.36x  30.51x  20.46x  16.77x  25.49x

--- VALUATION SUMMARY (Historical + Projected) ---
                              2022         2023         2024         2025        2026e        2027e        2028e        2029e        2030e
Market Cap             $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M  $1,465,229M
Net Debt                  $-4,653M     $-4,653M     $-4,653M     $-4,653M     $-4,653M     $-4,653M     $-4,653M     $-4,653M     $-4,653M
Net Debt / EBITDA           -0.12x       -0.08x       -0.05x       -0.04x       -0.04x       -0.04x       -0.03x       -0.03x       -0.03x
Enterprise Value (EV)  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M  $1,460,576M
PER                         63.16x       37.48x       23.50x       24.24x       19.26x       17.57x       15.56x       13.62x       12.00x
EV/FCF                      96.19x       38.54x       21.84x       23.94x       20.69x       17.94x       15.91x       13.76x       12.23x
EV/EBITDA                   38.75x       24.73x       16.81x       13.82x       13.08x       11.87x       10.52x        9.32x        8.23x
EV/EBIT                     50.36x       30.51x       20.46x       16.77x       16.32x       14.88x       13.18x       11.54x       10.16x

--- TARGET PRICES BY MULTIPLE ---
                           2026e  2027e  2028e   2029e   2030e
PER ex Cash                 $763   $835   $939  $1,070  $1,211
EV/FCF                      $688   $793   $894  $1,032  $1,162
EV/EBITDA                   $739   $814   $919  $1,037  $1,174
EV/EBIT                     $697   $764   $863    $985  $1,118
Average                     $722   $802   $904  $1,031  $1,166
---                          ---    ---    ---     ---     ---
CAGR PER ex Cash           32.3%  20.3%  17.6%   16.7%   16.0%
CAGR EV/FCF                19.1%  17.2%  15.7%   15.6%   15.0%
CAGR EV/EBITDA             28.1%  18.8%  16.8%   15.8%   15.3%
CAGR EV/EBIT               20.8%  15.1%  14.3%   14.3%   14.1%
CAGR Average               25.1%  17.8%  16.1%   15.6%   15.1%
----                        ----   ----   ----    ----    ----
Margin of Safety (EV/FCF)  16.1%  27.2%  35.4%   44.1%   50.3%
Upside Potential (EV/FCF)  19.1%  37.3%  54.8%   78.9%  101.2%

--- BUY PRICE FOR 15% ANNUAL RETURN ---
  Target Return                       15.0%
  Reference Year                      2026e
  EV/FCF Target Price                 $688
  Max Buy Price                       $597.90
  Current Price                       $577.22
  Difference vs Current               -3.5%
  Verdict                             BELOW target price — attractive entry